// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		int counterAboveHalf = 0, counterBelowHalf = 0;
		for (int i = 0; i < n; i++) {
			if (Math.random() > 0.5)
			counterAboveHalf++;
			else
			counterBelowHalf++;
		}
		double ratio;
		System.out.println("> 0.5: " + counterAboveHalf + " times");
		System.out.println("<= 0.5: " + counterBelowHalf + " times");
		if (counterAboveHalf != 0 && counterBelowHalf != 0) {
			ratio = (double)counterAboveHalf / counterBelowHalf;
			System.out.println("ratio: " + ratio);		
		}

	}
}
